services:
  - type: web
    name: whisky-gallery-backend
    runtime: java
    plan: free
    build:
      command: "./mvnw clean package -DskipTests"
    start:
      command: "java -jar target/whisky-0.0.1-SNAPSHOT.jar"
